sonar.projectKey=DiarSpeicher
sonar.projectName=DiarSpeicher
sonar.sourceEncoding=UTF-8

sonar.sources=src,frontEnd/src
sonar.tests=tests

sonar.exclusions=\
  **/bin/**,\
  **/obj/**,\
  **/node_modules/**,\
  **/dist/**,\
  src/DiarSpeicher.Infrastructure/Migrations/**


sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=csharpsquid:S2325
sonar.issue.ignore.multicriteria.e1.resourceKey=src/DiarSpeicher.Infrastructure/Data/DiarSpeicherDbContext.cs
