// <auto-generated />
using System;
using DiarSpeicher.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiarSpeicher.Infrastructure.Migrations
{
    [DbContext(typeof(DiarSpeicherDbContext))]
    partial class DiarSpeicherDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.AgeRestriction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RestrictOnUnset")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AgeRestrictions");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.ApiKey", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.Library", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Emoji")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailMeta")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigId")
                        .IsUnique();

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.LibraryConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ConvertRarToZip")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultLibraryViewMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultReadingDir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultReadingMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("GenerateFileHashes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GenerateKoreaderHashes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HardDeleteConversions")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideSeriesView")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IgnoreRules")
                        .HasColumnType("TEXT");

                    b.Property<string>("LibraryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LibraryPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LibraryType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ProcessMetadata")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThumbnailHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThumbnailWidth")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Watch")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LibraryConfigs");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.LibraryExclusion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LibraryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.HasIndex("UserId");

                    b.ToTable("LibraryExclusions");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.Media", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .HasColumnType("TEXT");

                    b.Property<string>("KoreaderHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Pages")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailMeta")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("Hash");

                    b.HasIndex("KoreaderHash");

                    b.HasIndex("Path");

                    b.HasIndex("SeriesId");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.MediaMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AgeRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Characters")
                        .HasColumnType("TEXT");

                    b.Property<string>("Colorists")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverArtists")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Editors")
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentifierAmazon")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentifierCalibre")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentifierGoogle")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentifierIsbn")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentifierMobiAsin")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentifierUuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Inkers")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("Letterers")
                        .HasColumnType("TEXT");

                    b.Property<string>("Links")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Number")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pencillers")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT");

                    b.Property<string>("Series")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesGroup")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoryArc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("StoryArcNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Teams")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleSort")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Volume")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Writers")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaId")
                        .IsUnique();

                    b.ToTable("MediaMetadata");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.MediaTag", b =>
                {
                    b.Property<string>("MediaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("MediaTags");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.ReadingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ElapsedSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndPage")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("EndPercentage")
                        .HasColumnType("TEXT");

                    b.Property<string>("KoreaderProgress")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReadthroughNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartPage")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("StartPercentage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("UserId", "MediaId");

                    b.ToTable("ReadingSessions");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.ScannedDirectory", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastMTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Path");

                    b.ToTable("ScannedDirectories");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.Series", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("LibraryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailMeta")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.HasIndex("Path");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.SeriesMetadata", b =>
                {
                    b.Property<string>("SeriesId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("AgeRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Booktype")
                        .HasColumnType("TEXT");

                    b.Property<string>("Characters")
                        .HasColumnType("TEXT");

                    b.Property<string>("ComicImage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Comicid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionFormatted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<string>("Imprint")
                        .HasColumnType("TEXT");

                    b.Property<string>("Links")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaType")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicationRun")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalIssues")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Volume")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Writers")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("SeriesId");

                    b.ToTable("SeriesMetadata");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.SeriesTag", b =>
                {
                    b.Property<string>("SeriesId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SeriesId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("SeriesTags");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.Session", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarMeta")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AvatarUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedPassword")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsServerOwner")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxSessionsAllowed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OidcEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("OidcIssuerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Permissions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.UserPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppFont")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppTheme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableCompactDisplay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.AgeRestriction", b =>
                {
                    b.HasOne("DiarSpeicher.Core.Domain.Entities.User", "User")
                        .WithOne("AgeRestriction")
                        .HasForeignKey("DiarSpeicher.Core.Domain.Entities.AgeRestriction", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.ApiKey", b =>
                {
                    b.HasOne("DiarSpeicher.Core.Domain.Entities.User", "User")
                        .WithMany("ApiKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.Library", b =>
                {
                    b.HasOne("DiarSpeicher.Core.Domain.Entities.LibraryConfig", "Config")
                        .WithOne("Library")
                        .HasForeignKey("DiarSpeicher.Core.Domain.Entities.Library", "ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Config");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.LibraryExclusion", b =>
                {
                    b.HasOne("DiarSpeicher.Core.Domain.Entities.Library", "Library")
                        .WithMany("ExcludedUsers")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiarSpeicher.Core.Domain.Entities.User", null)
                        .WithMany("ExcludedLibraries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.Media", b =>
                {
                    b.HasOne("DiarSpeicher.Core.Domain.Entities.Series", "Series")
                        .WithMany("Media")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Series");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.MediaMetadata", b =>
                {
                    b.HasOne("DiarSpeicher.Core.Domain.Entities.Media", "Media")
                        .WithOne("Metadata")
                        .HasForeignKey("DiarSpeicher.Core.Domain.Entities.MediaMetadata", "MediaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Media");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.MediaTag", b =>
                {
                    b.HasOne("DiarSpeicher.Core.Domain.Entities.Media", "Media")
                        .WithMany("Tags")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiarSpeicher.Core.Domain.Entities.Tag", "Tag")
                        .WithMany("MediaTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.ReadingSession", b =>
                {
                    b.HasOne("DiarSpeicher.Core.Domain.Entities.Media", "Media")
                        .WithMany("ReadingSessions")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiarSpeicher.Core.Domain.Entities.User", "User")
                        .WithMany("ReadingSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.Series", b =>
                {
                    b.HasOne("DiarSpeicher.Core.Domain.Entities.Library", "Library")
                        .WithMany("Series")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Library");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.SeriesMetadata", b =>
                {
                    b.HasOne("DiarSpeicher.Core.Domain.Entities.Series", "Series")
                        .WithOne("Metadata")
                        .HasForeignKey("DiarSpeicher.Core.Domain.Entities.SeriesMetadata", "SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.SeriesTag", b =>
                {
                    b.HasOne("DiarSpeicher.Core.Domain.Entities.Series", "Series")
                        .WithMany("Tags")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiarSpeicher.Core.Domain.Entities.Tag", "Tag")
                        .WithMany("SeriesTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.Session", b =>
                {
                    b.HasOne("DiarSpeicher.Core.Domain.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.UserPreferences", b =>
                {
                    b.HasOne("DiarSpeicher.Core.Domain.Entities.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("DiarSpeicher.Core.Domain.Entities.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.Library", b =>
                {
                    b.Navigation("ExcludedUsers");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.LibraryConfig", b =>
                {
                    b.Navigation("Library");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.Media", b =>
                {
                    b.Navigation("Metadata");

                    b.Navigation("ReadingSessions");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.Series", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("Metadata");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.Tag", b =>
                {
                    b.Navigation("MediaTags");

                    b.Navigation("SeriesTags");
                });

            modelBuilder.Entity("DiarSpeicher.Core.Domain.Entities.User", b =>
                {
                    b.Navigation("AgeRestriction");

                    b.Navigation("ApiKeys");

                    b.Navigation("ExcludedLibraries");

                    b.Navigation("Preferences");

                    b.Navigation("ReadingSessions");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
